### ISSUE TITLE
Flag package as out of date

### ISSUE THREAD

**Issue by romulasry** [rpm-software-management/createrepo_c#247]
Doable?
Needed for https://github.com/openSUSE/zypper/issues/376

**Comment by kontura** [comment]
Can you describe the request more?

You want to create a repository from a set of rpms but flag some of the packages as out of date? What would out of date mean for a package?

**Comment by romulasry** [comment]
It would mean you have to check if the version if greater than the current version before removing that flag when the package is updated. Example 2.33 to 2.34 in VERSION would remove the flag for example.

**Comment by kontura** [comment]
So you as the person making the repository want to flag some packages out of date (because you somehow know there is a new upstream release). The packager would then run some command like `dnf list --out-of-date`, this prints all the packages flagged and he can go and build updated rpms, which you can then include when you update the repository next time.

If I understand correctly the packager has to remember to run `dnf list --out-of-date` (or some such command) shouldn't he just check if any of his packages need updating instead of relying on the person making the repository?

**Comment by Conan-Kudo** [comment]
This makes no sense at the createrepo_c level. All we do is extract the metadata of RPMs and turn it into something that package managers can fetch and parse. If you want something like this on the openSUSE side, you'd want something like [release-monitoring.org](https://release-monitoring.org/) integration with the openSUSE Build Service.
