### ISSUE TITLE
No package 'libmagic' found

### ISSUE THREAD

**Issue by jringoot** [rpm-software-management/createrepo_c#300]
[CMakeOutput.log](https://github.com/rpm-software-management/createrepo_c/files/7727801/CMakeOutput.log)
Although it is installed

> apt search libmagic-dev
> Sorting... Done
> Full Text Search... Done
> libmagic-dev/focal,now 1:5.38-4 amd64 [installed]
>   Recognize the type of data in a file using "magic" numbers - development
> 

Still 

> cmake ..
> CMake Deprecation Warning at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- Checking for module 'libmagic'
> --   No package 'libmagic' found
> -- Checking for module 'zck'
> --   No package 'zck' found
> CMake Error at /opt/cobbler/cobbler/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
>   A required package was not found
> Call Stack (most recent call first):
>   /opt/cobbler/cobbler/lib/python3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
>   CMakeLists.txt:83 (pkg_check_modules)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/opt/createrepo_c/build/CMakeFiles/CMakeOutput.log".
>

**Comment by kontura** [comment]
There is a missing `/usr/lib/x86_64-linux-gnu/pkgconfig/libmagic.pc` file, it seems it is added in [`libmagic-dev (1:5.39-3)`](https://packages.ubuntu.com/hirsute/amd64/libmagic-dev/filelist) but you have only [`libmagic-dev (1:5.38-4)`](https://packages.ubuntu.com/focal/amd64/libmagic-dev/filelist).

However `libmagic` is not required in createrepo_c's cmake it should build without it, I think the problem is `zck`. If you have it available you can install [`libzck-dev`](https://packages.ubuntu.com/impish/libzck-dev) otherwise compile without zchunk support: `-DWITH_ZCHUNK=OFF`.
(Same goes for [`libmodulemd-dev`](https://packages.ubuntu.com/hirsute/libmodulemd-dev): `-DWITH_LIBMODULEMD=OFF`, both zchunk and libmodulemd are ON by default.)
