### ISSUE TITLE
Improper use of errno causing incorrect GError messages

### ISSUE THREAD

**Issue by cottsay** [rpm-software-management/createrepo_c#320]
The following pattern appears throughout `createrepo_c`:
```c
rc = do_thing();
if (rc) {
    g_warning("%s: Failure: %s", __func__, g_strerror(errno));
    g_set_error(err, ERR_DOMAIN, CRE_IO, "Failure: %s", g_strerror(errno));
}
```

The `errno` value can be changed by the call to `g_warning`, so the GError gets populated with the wrong message. For example, calling `cr_package_from_rpm` on a non-existent package will result in the following warning in the log:
`read_header: Fopen of foo.bar failed No such file or directory`
...while the following message is returned in the GError on my machine: 
`Fopen failed: Socket operation on non-socket`

The following change resulted in the correct behavior:
```diff
--- a/src/parsepkg.c
+++ b/src/parsepkg.c
@@ -92,10 +92,11 @@ read_header(const char *filename, Header *hdr, GError **err)
 
     FD_t fd = Fopen(filename, "r.ufdio");
     if (!fd) {
+        int fopen_error = errno;
         g_warning("%s: Fopen of %s failed %s",
-                  __func__, filename, g_strerror(errno));
+                  __func__, filename, g_strerror(fopen_error));
         g_set_error(err, ERR_DOMAIN, CRE_IO,
-                    "Fopen failed: %s", g_strerror(errno));
+                    "Fopen failed: %s", g_strerror(fopen_error));
         return FALSE;
     }
 
```

I'd be happy to help resolve this issue by opening a pull request, but there will be a lot of changes and I want to make sure I'm not missing something obvious before spending the time to make the changes.

Thanks!

**Comment by kontura** [comment]
I am able to reproduce this and interestingly I think the change is not caused by the call to `g_warning()` but the call to `g_strerror()` because if I change it to just `strerror()` the messages in both error and warning are the same.

The [docs](https://docs.gtk.org/glib/func.strerror.html) for `g_strerror()` say it shouldn't change `errno` but that it should be saved anyway...

So it is a problem and we would welcome PRs. :+1:
