### ISSUE TITLE
Add option to createrepo_c to only update certain packages

### ISSUE THREAD

**Issue by jailbird777** [rpm-software-management/createrepo_c#46]
I have a repo with many many thousands of packages in it.  The repos are updated by a scheduled job that know exactly while packages have been updated/added/deleted, but as far as I'm aware there's no way to tell createrepo_c --update to only bother looking for changes in those packages.  As far as I'm aware, --pkglist and/or --includepkg with the --update option won't do this, as they'll remove the packages that don't match, I believe.  Maybe the --keep-all-metadata option?

Either that isn't currently possible, or the man pages could use some clarifying.

**Comment by olivier427** [comment]
I would be interested to know more about this too. It would be nice to be able to append metadata for only a specific list of packages.

**Comment by kontura** [comment]
If this is still interesting for you, I looked into it and thought of a couple of options, however none do exactly what you want. You could try:
1. Use --pkglist and create repo of only your new packages and then mergerepo_c your new repo and old repo.
2. Look into --skip-stat if you can be sure your updated packages always change name.
3. Use the --update and --excludes option which is kind of complementary to what option you would want if I understand correctly. You could generate the createrepo_c command which would list (e.g. -x pgk1 -x pkg2 ...) all your packages except those you know were updated/added/deleted. Though the command would be very long. 

One thing to note I haven't been able to get any significant speed up in execution, because I think most of the work is done when handling the already big repodata files and this is unavoidable. 

Is any of this helpful?
