### ISSUE TITLE
comps.xml has doctype with invalid dtd reference

### ISSUE THREAD

**Issue by bmbouter** [rpm-software-management/createrepo_c#62]
Consider the [latest Fedora compose](http://ftp.linux.ncsu.edu/pub/fedora/linux/releases/24/Server/x86_64/os/repodata/) which uses createrepo_c. Look at the comps.xml file. you'll see something like this:

```
<!DOCTYPE comps PUBLIC "-//Red Hat, Inc.//DTD Comps info//EN" "comps.dtd">
```

It would be more correct to use this one:  https://pagure.io/fedora-comps/blob/master/f/comps.dtd

I've also written some about other options here:  https://pulp.plan.io/issues/1786#note-4

**Comment by kontura** [comment]
This problem seems to be still present even on [current](http://ftp.linux.ncsu.edu/pub/fedora/linux/releases/30/Server/x86_64/os/repodata/) comps.xml. However createrepo_c is not generating these group files. It is only able to add it to repodata, either when creating them with `createrepo_c -g /path/to/comps.xml .` or later with `modifyrepo_c /path/to/comps.xml .`.

Repodata xml files created by createrepo_c are missing dtd references altogether, but that is probably a separate issue.
