### ISSUE TITLE
retain-old-md doesn't seem to work

### ISSUE THREAD

**Issue by gfrankliu** [rpm-software-management/createrepo_c#79]
I am using "createrepo_c --update --retain-old-md 4 ." and the files in repodata keeps growing after each run. Does --retain-old-md option work for anyone? Am I missing something?

**Comment by amoralej** [comment]
I'm hitting a similar issue, any update?

**Comment by esproul** [comment]
I have this issue too, using 0.10.0 from EPEL on CentOS 7.

**Comment by kontura** [comment]
I have looked into this and there is a change in behavior that is not documented. It works like this:

By default `--retain-old-md` with 0 specified removes all files present in repomd.xml from the old repository. Any other number keeps all files untouched (except for repomd.xml because it doesn't have unique name).

However there is another option `--compatibility` which makes the `--retain-old-md` option work in the same way as it did in the original createrepo, which is the way its documented even in createrepo_c.
Its explained in the code that this a bad method because it matches the files by name and can handle only the standard: primary, filelists, other and their DB variants, it can't handle any additional repodata (groups, updateinfos, modules...).

I will create a PR to reflect this behavior in documentation.
