### ISSUE TITLE
Modularity Support

### ISSUE THREAD

**Issue by bmbouter** [rpm-software-management/createrepo_c#98]
With the modularity metadata formats being added to Fedora 28, the createrepo_c tooling will also needs updates to interact with that metadata format.

[Our software](http://pulpproject.org/) uses the createrepo_c Python bindings to parse and generate rpm metadata so we're blocked on managing that content type without this support.

**Comment by dkliban** [comment]
createrepo_c needs to be able to inspect the RPMs and determine if it belongs to a module or not. If it belongs to a module, createrepo_c needs to produce an error if the relevant modulemd information is missing from the repository. 

Until this feature is added, Pulp is going to have to perform this enforcement before running createrepo_c to generate the repository metadata.

**Comment by Conan-Kudo** [comment]
Module metadata is not really the concern of createrepo_c (or if it is, then AppStream metadata should be too!). Since module definitions are stored entirely in Koji and are built from that process, then that build system _must_ export it and tools handling it must know to handle that metadata content properly.

**Comment by Conan-Kudo** [comment]
Limited modulemd handling is now supported in v0.13.0.
